[project]
name = 'rube_contracts'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.immutable_depot]
path = 'contracts/immutable_depot.clar'
clarity_version = 2
epoch = 2.5

[contracts.token_integration]
path = 'contracts/token_integration.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
